../$(OBJS_DIR)/main.o:main.c ECHO
	$(CC) -c main.c -o main

LYP_FLAGS += YW

ECHO:
	@echo lyp cc is  $(CC)
	@echo lyp OBJ is  $(OBJ)
	@echo lyp bin is  $(BIN)
	@echo lyp OBJS_DIR is  $(OBJS_DIR)
	@echo lyp DIN_DIR is  $(BIN_DIR)
	@echo lyp flags is $(LYP_FLAGS)
